{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1d7777f0-e994-4a69-9572-469a3550e2af",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "# Note: Here Exception class refers to the base class for all the exceptions.\n",
    "\n",
    "\"\"\"\n",
    "Built-in exceptions offer information about Python-related problems, and custom exceptions will \n",
    "add information about project-related problems. That way, you can design your code (and traceback, \n",
    "if an exception is raised) in a way that combines Python code with the language of the project.\n",
    "\"\"\"\n",
    "# BaseException is the common base class of all exceptions. One of its subclasses, Exception , \n",
    "# is the base class of all the non-fatal exceptions. Exceptions which are not subclasses of Exception \n",
    "# are not typically handled, because they are used to indicate that the program should terminate.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6ed7f129-8a8e-4176-a0d9-bdd1b288da87",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Q2. Write a python program to print Python Exception Hierarchy.\n",
    "\n",
    "\"\"\"\n",
    "There are many Built-in Exceptions in Python let’s try to print them out in a hierarchy.\n",
    "\n",
    "For printing the tree hierarchy we will use inspect module in Python. \n",
    "The inspect module provides useful functions to get information about objects such as \n",
    "modules, classes, methods, functions,  and code objects. For example, it can help you \n",
    "examine the contents of a class, extract and format the argument list for a function.\n",
    "\n",
    "For building a tree hierarchy we will use inspect.getclasstree().\n",
    "\n",
    "        Syntax: inspect.getclasstree(classes, unique=False)\n",
    "\"\"\"\n",
    "\n",
    "# \"inspect.getclasstree()\" arranges the given list of classes into a hierarchy of nested lists. \n",
    "# Where a nested list appears, it contains classes derived from the class whose entry immediately precedes the \n",
    "# list.If the unique argument is true, exactly one entry appears in the returned structure for each class in the \n",
    "# given list. Otherwise, classes using multiple inheritance and their descendants will appear multiple times.\n",
    "\n",
    "\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b9e327e5-65de-4448-aba2-917a51d0d838",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " BaseException\n",
      "--- Exception\n",
      "------ TypeError\n",
      "--------- FloatOperation\n",
      "--------- MultipartConversionError\n",
      "------ StopAsyncIteration\n",
      "------ StopIteration\n",
      "------ ImportError\n",
      "--------- ModuleNotFoundError\n",
      "--------- ZipImportError\n",
      "------ OSError\n",
      "--------- ConnectionError\n",
      "------------ BrokenPipeError\n",
      "------------ ConnectionAbortedError\n",
      "------------ ConnectionRefusedError\n",
      "------------ ConnectionResetError\n",
      "--------------- RemoteDisconnected\n",
      "--------- BlockingIOError\n",
      "--------- ChildProcessError\n",
      "--------- FileExistsError\n",
      "--------- FileNotFoundError\n",
      "--------- IsADirectoryError\n",
      "--------- NotADirectoryError\n",
      "--------- InterruptedError\n",
      "------------ InterruptedSystemCall\n",
      "--------- PermissionError\n",
      "--------- ProcessLookupError\n",
      "--------- TimeoutError\n",
      "--------- UnsupportedOperation\n",
      "--------- itimer_error\n",
      "--------- herror\n",
      "--------- gaierror\n",
      "--------- SSLError\n",
      "------------ SSLCertVerificationError\n",
      "------------ SSLZeroReturnError\n",
      "------------ SSLWantWriteError\n",
      "------------ SSLWantReadError\n",
      "------------ SSLSyscallError\n",
      "------------ SSLEOFError\n",
      "--------- Error\n",
      "------------ SameFileError\n",
      "--------- SpecialFileError\n",
      "--------- ExecError\n",
      "--------- ReadError\n",
      "--------- URLError\n",
      "------------ HTTPError\n",
      "------------ ContentTooShortError\n",
      "--------- BadGzipFile\n",
      "------ EOFError\n",
      "--------- IncompleteReadError\n",
      "------ RuntimeError\n",
      "--------- RecursionError\n",
      "--------- NotImplementedError\n",
      "------------ ZMQVersionError\n",
      "------------ StdinNotImplementedError\n",
      "--------- _DeadlockError\n",
      "--------- BrokenBarrierError\n",
      "--------- BrokenExecutor\n",
      "------------ BrokenThreadPool\n",
      "--------- SendfileNotAvailableError\n",
      "--------- ExtractionError\n",
      "--------- VariableError\n",
      "------ NameError\n",
      "--------- UnboundLocalError\n",
      "------ AttributeError\n",
      "--------- FrozenInstanceError\n",
      "------ SyntaxError\n",
      "--------- IndentationError\n",
      "------------ TabError\n",
      "------ LookupError\n",
      "--------- IndexError\n",
      "--------- KeyError\n",
      "------------ NoSuchKernel\n",
      "------------ UnknownBackend\n",
      "--------- CodecRegistryError\n",
      "------ ValueError\n",
      "--------- UnicodeError\n",
      "------------ UnicodeEncodeError\n",
      "------------ UnicodeDecodeError\n",
      "------------ UnicodeTranslateError\n",
      "--------- UnsupportedOperation\n",
      "--------- JSONDecodeError\n",
      "--------- SSLCertVerificationError\n",
      "--------- Error\n",
      "--------- UnsupportedDigestmodError\n",
      "--------- IllegalMonthError\n",
      "--------- IllegalWeekdayError\n",
      "--------- ParserError\n",
      "--------- ClassNotFound\n",
      "--------- ClipboardEmpty\n",
      "--------- MessageDefect\n",
      "------------ NoBoundaryInMultipartDefect\n",
      "------------ StartBoundaryNotFoundDefect\n",
      "------------ CloseBoundaryNotFoundDefect\n",
      "------------ FirstHeaderLineIsContinuationDefect\n",
      "------------ MisplacedEnvelopeHeaderDefect\n",
      "------------ MissingHeaderBodySeparatorDefect\n",
      "------------ MultipartInvariantViolationDefect\n",
      "------------ InvalidMultipartContentTransferEncodingDefect\n",
      "------------ UndecodableBytesDefect\n",
      "------------ InvalidBase64PaddingDefect\n",
      "------------ InvalidBase64CharactersDefect\n",
      "------------ InvalidBase64LengthDefect\n",
      "------------ HeaderDefect\n",
      "--------------- InvalidHeaderDefect\n",
      "--------------- HeaderMissingRequiredValue\n",
      "--------------- NonPrintableDefect\n",
      "--------------- ObsoleteHeaderDefect\n",
      "--------------- NonASCIILocalPartDefect\n",
      "--------------- InvalidDateDefect\n",
      "--------- MacroToEdit\n",
      "--------- InvalidFileException\n",
      "--------- UnequalIterablesError\n",
      "--------- InvalidVersion\n",
      "--------- _InvalidELFFileHeader\n",
      "--------- InvalidWheelFilename\n",
      "--------- InvalidSdistFilename\n",
      "--------- InvalidSpecifier\n",
      "--------- InvalidMarker\n",
      "--------- UndefinedComparison\n",
      "--------- UndefinedEnvironmentName\n",
      "--------- InvalidRequirement\n",
      "------------ RequirementParseError\n",
      "--------- InvalidVersion\n",
      "------ AssertionError\n",
      "------ ArithmeticError\n",
      "--------- FloatingPointError\n",
      "--------- OverflowError\n",
      "--------- ZeroDivisionError\n",
      "------------ DivisionByZero\n",
      "------------ DivisionUndefined\n",
      "--------- DecimalException\n",
      "------------ Clamped\n",
      "------------ Rounded\n",
      "--------------- Underflow\n",
      "--------------- Overflow\n",
      "------------ Inexact\n",
      "--------------- Underflow\n",
      "--------------- Overflow\n",
      "------------ Subnormal\n",
      "--------------- Underflow\n",
      "------------ DivisionByZero\n",
      "------------ FloatOperation\n",
      "------------ InvalidOperation\n",
      "--------------- ConversionSyntax\n",
      "--------------- DivisionImpossible\n",
      "--------------- DivisionUndefined\n",
      "--------------- InvalidContext\n",
      "------ SystemError\n",
      "--------- CodecRegistryError\n",
      "------ ReferenceError\n",
      "------ MemoryError\n",
      "------ BufferError\n",
      "------ Warning\n",
      "--------- UserWarning\n",
      "------------ GetPassWarning\n",
      "------------ FormatterWarning\n",
      "--------- EncodingWarning\n",
      "--------- DeprecationWarning\n",
      "------------ ProvisionalWarning\n",
      "--------- PendingDeprecationWarning\n",
      "--------- SyntaxWarning\n",
      "--------- RuntimeWarning\n",
      "------------ ProactorSelectorThreadWarning\n",
      "------------ UnknownTimezoneWarning\n",
      "------------ PEP440Warning\n",
      "--------- FutureWarning\n",
      "------------ ProvisionalCompleterWarning\n",
      "--------- ImportWarning\n",
      "--------- UnicodeWarning\n",
      "--------- BytesWarning\n",
      "--------- ResourceWarning\n",
      "--------- DeprecatedTzFormatWarning\n",
      "--------- PkgResourcesDeprecationWarning\n",
      "------ _OptionError\n",
      "------ _Error\n",
      "------ error\n",
      "------ Verbose\n",
      "------ Error\n",
      "------ SubprocessError\n",
      "--------- CalledProcessError\n",
      "--------- TimeoutExpired\n",
      "------ TokenError\n",
      "------ StopTokenizing\n",
      "------ ClassFoundException\n",
      "------ EndOfBlock\n",
      "------ TraitError\n",
      "------ Error\n",
      "------ Error\n",
      "--------- CancelledError\n",
      "--------- TimeoutError\n",
      "--------- InvalidStateError\n",
      "------ _GiveupOnSendfile\n",
      "------ error\n",
      "------ Incomplete\n",
      "------ TimeoutError\n",
      "------ InvalidStateError\n",
      "------ LimitOverrunError\n",
      "------ QueueEmpty\n",
      "------ QueueFull\n",
      "------ Empty\n",
      "------ Full\n",
      "------ ArgumentError\n",
      "------ ZMQBaseError\n",
      "--------- ZMQError\n",
      "------------ ContextTerminated\n",
      "------------ Again\n",
      "------------ InterruptedSystemCall\n",
      "--------- ZMQBindError\n",
      "--------- NotDone\n",
      "------ PickleError\n",
      "--------- PicklingError\n",
      "--------- UnpicklingError\n",
      "------ _Stop\n",
      "------ ArgumentError\n",
      "------ ArgumentTypeError\n",
      "------ ConfigError\n",
      "--------- ConfigLoaderError\n",
      "------------ ArgumentError\n",
      "--------- ConfigFileNotFound\n",
      "------ ConfigurableError\n",
      "--------- MultipleInstanceError\n",
      "------ ApplicationError\n",
      "------ error\n",
      "------ TimeoutError\n",
      "------ error\n",
      "------ ReturnValueIgnoredError\n",
      "------ KeyReuseError\n",
      "------ UnknownKeyError\n",
      "------ LeakedCallbackError\n",
      "------ BadYieldError\n",
      "------ ReturnValueIgnoredError\n",
      "------ Return\n",
      "------ InvalidPortNumber\n",
      "------ error\n",
      "------ LZMAError\n",
      "------ RegistryError\n",
      "------ _GiveupOnFastCopy\n",
      "------ Error\n",
      "--------- NoSectionError\n",
      "--------- DuplicateSectionError\n",
      "--------- DuplicateOptionError\n",
      "--------- NoOptionError\n",
      "--------- InterpolationError\n",
      "------------ InterpolationMissingOptionError\n",
      "------------ InterpolationSyntaxError\n",
      "------------ InterpolationDepthError\n",
      "--------- ParsingError\n",
      "------------ MissingSectionHeaderError\n",
      "------ NoIPAddresses\n",
      "------ BadZipFile\n",
      "------ LargeZipFile\n",
      "------ BadEntryPoint\n",
      "------ NoSuchEntryPoint\n",
      "------ DuplicateKernelError\n",
      "------ ErrorDuringImport\n",
      "------ NotOneValueFound\n",
      "------ CannotEval\n",
      "------ OptionError\n",
      "------ BdbQuit\n",
      "------ Restart\n",
      "------ ExceptionPexpect\n",
      "--------- EOF\n",
      "--------- TIMEOUT\n",
      "------ PtyProcessError\n",
      "------ FindCmdError\n",
      "------ HomeDirError\n",
      "------ ProfileDirError\n",
      "------ IPythonCoreError\n",
      "--------- TryNext\n",
      "--------- UsageError\n",
      "--------- StdinNotImplementedError\n",
      "------ InputRejected\n",
      "------ GetoptError\n",
      "------ ErrorToken\n",
      "------ PrefilterError\n",
      "------ AliasError\n",
      "--------- InvalidAliasError\n",
      "------ Error\n",
      "--------- InterfaceError\n",
      "--------- DatabaseError\n",
      "------------ InternalError\n",
      "------------ OperationalError\n",
      "------------ ProgrammingError\n",
      "------------ IntegrityError\n",
      "------------ DataError\n",
      "------------ NotSupportedError\n",
      "------ Warning\n",
      "------ SpaceInInput\n",
      "------ DOMException\n",
      "--------- IndexSizeErr\n",
      "--------- DomstringSizeErr\n",
      "--------- HierarchyRequestErr\n",
      "--------- WrongDocumentErr\n",
      "--------- InvalidCharacterErr\n",
      "--------- NoDataAllowedErr\n",
      "--------- NoModificationAllowedErr\n",
      "--------- NotFoundErr\n",
      "--------- NotSupportedErr\n",
      "--------- InuseAttributeErr\n",
      "--------- InvalidStateErr\n",
      "--------- SyntaxErr\n",
      "--------- InvalidModificationErr\n",
      "--------- NamespaceErr\n",
      "--------- InvalidAccessErr\n",
      "--------- ValidationErr\n",
      "------ ValidationError\n",
      "------ EditReadOnlyBuffer\n",
      "------ _Retry\n",
      "------ InvalidLayoutError\n",
      "------ HeightIsUnknownError\n",
      "------ ParserSyntaxError\n",
      "------ InternalParseError\n",
      "------ _PositionUpdatingFinished\n",
      "------ SimpleGetItemNotFound\n",
      "------ UncaughtAttributeError\n",
      "------ HasNoContext\n",
      "------ ParamIssue\n",
      "------ _JediError\n",
      "--------- InternalError\n",
      "--------- WrongVersion\n",
      "--------- RefactoringError\n",
      "------ OnErrorLeaf\n",
      "------ InvalidPythonEnvironment\n",
      "------ MessageError\n",
      "--------- MessageParseError\n",
      "------------ HeaderParseError\n",
      "------------ BoundaryError\n",
      "--------- MultipartConversionError\n",
      "--------- CharsetError\n",
      "------ Error\n",
      "------ HTTPException\n",
      "--------- NotConnected\n",
      "--------- InvalidURL\n",
      "--------- UnknownProtocol\n",
      "--------- UnknownTransferEncoding\n",
      "--------- UnimplementedFileMode\n",
      "--------- IncompleteRead\n",
      "--------- ImproperConnectionState\n",
      "------------ CannotSendRequest\n",
      "------------ CannotSendHeader\n",
      "------------ ResponseNotReady\n",
      "--------- BadStatusLine\n",
      "------------ RemoteDisconnected\n",
      "--------- LineTooLong\n",
      "------ InteractivelyDefined\n",
      "------ KillEmbedded\n",
      "------ Error\n",
      "--------- NoSuchProcess\n",
      "------------ ZombieProcess\n",
      "--------- AccessDenied\n",
      "--------- TimeoutExpired\n",
      "------ _Ipv6UnsupportedError\n",
      "------ QueueEmpty\n",
      "------ QueueFull\n",
      "------ DebuggerInitializationError\n",
      "------ ExpatError\n",
      "------ Error\n",
      "--------- ProtocolError\n",
      "--------- ResponseError\n",
      "--------- Fault\n",
      "------ ParseBaseException\n",
      "--------- ParseException\n",
      "--------- ParseFatalException\n",
      "------------ ParseSyntaxException\n",
      "------ RecursiveGrammarException\n",
      "------ ResolutionError\n",
      "--------- VersionConflict\n",
      "------------ ContextualVersionConflict\n",
      "--------- DistributionNotFound\n",
      "--------- UnknownExtra\n",
      "------ _Error\n",
      "------ UnableToResolveVariableException\n",
      "------ InvalidTypeInArgsException\n",
      "--- GeneratorExit\n",
      "--- SystemExit\n",
      "--- KeyboardInterrupt\n",
      "--- CancelledError\n",
      "--- AbortThread\n"
     ]
    }
   ],
   "source": [
    "# Let’s write a code for printing tree hierarchy for built-in exceptions:\n",
    "\n",
    "# import inspect module\n",
    "import inspect\n",
    "  \n",
    "# our treeClass function\n",
    "def treeClass(cls, ind = 0):\n",
    "    \n",
    "      # print name of the class\n",
    "    print ('-' * ind, cls.__name__)\n",
    "      \n",
    "    # iterating through subclasses\n",
    "    for i in cls.__subclasses__():\n",
    "        treeClass(i, ind + 3)\n",
    "#print(\"Hierarchy for Built-in exceptions is : \")\n",
    "# inspect.getmro() Return a tuple \n",
    "# of class  cls’s base classes.\n",
    "  \n",
    "# building a tree hierarchy \n",
    "inspect.getclasstree(inspect.getmro(BaseException))\n",
    "  \n",
    "# function call\n",
    "treeClass(BaseException)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "34ec8342-5eb8-4677-b92e-c75ea7398770",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "\n",
    "\"\"\"\n",
    "ArithmeticError is simply an error that occurs during numeric calculations.\n",
    "\n",
    "ArithmeticError types in Python include:\n",
    "\n",
    "1. OverFlowError\n",
    "2. ZeroDivisionError\n",
    "3. FloatingPointError\n",
    "\n",
    "These errors are all capable of crashing a code in Python. \n",
    "It is essential to catch an error because you do not want your code to crash as a result of incorrect input \n",
    "from you or a user.\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "372671f0-ac49-4847-9866-93ecf76cff58",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "5.0\n",
      "25.0\n",
      "15625.0\n",
      "5.960464477539062e+16\n",
      "7.52316384526264e+83\n"
     ]
    },
    {
     "ename": "OverflowError",
     "evalue": "(34, 'Numerical result out of range')",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mOverflowError\u001b[0m                             Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[5], line 8\u001b[0m\n\u001b[1;32m      5\u001b[0m j \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m5.0\u001b[39m\n\u001b[1;32m      7\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m i \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mrange\u001b[39m(\u001b[38;5;241m1\u001b[39m, \u001b[38;5;241m1000\u001b[39m):\n\u001b[0;32m----> 8\u001b[0m     j \u001b[38;5;241m=\u001b[39m \u001b[43mj\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mi\u001b[49m\n\u001b[1;32m      9\u001b[0m     \u001b[38;5;28mprint\u001b[39m(j)\n",
      "\u001b[0;31mOverflowError\u001b[0m: (34, 'Numerical result out of range')"
     ]
    }
   ],
   "source": [
    "# 1. OverFlowError\n",
    "\n",
    "# An OverflowError exception is raised when an arithmetic operation exceeds the limits to be represented. \n",
    "# This is part of the ArithmeticError Exception class.\n",
    "j = 5.0\n",
    "\n",
    "for i in range(1, 1000):\n",
    "    j = j**i\n",
    "    print(j)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bbdbcdf7-8694-42b7-8194-d492789ecfcd",
   "metadata": {},
   "outputs": [],
   "source": [
    "# As you can see, when you are trying to calculate the exponent of a floating point number, \n",
    "# it fails at a certain stage with OverflowError exception. You can handle this error using \n",
    "# the OverflowError Exception class in Python."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "035bf4bc-c088-4efc-84ac-2fb1efcea2ff",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "5.0\n",
      "25.0\n",
      "15625.0\n",
      "5.960464477539062e+16\n",
      "7.52316384526264e+83\n",
      "Overflow error happened\n",
      "(34, 'Numerical result out of range'), <class 'OverflowError'>\n"
     ]
    }
   ],
   "source": [
    "# Handling OverflowError in Python\n",
    "j = 5.0\n",
    "\n",
    "try:\n",
    "    for i in range(1, 1000):\n",
    "        j = j**i\n",
    "        print(j)\n",
    "except OverflowError as e:\n",
    "    print(\"Overflow error happened\")\n",
    "    print(f\"{e}, {e.__class__}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "f00f5b20-cb5d-4cb6-9f5e-6c2b0295ecd5",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[3], line 6\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m# 1. ZeroDivisionError\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \n\u001b[1;32m      3\u001b[0m \u001b[38;5;66;03m# How to identify an ArithmeticError:\u001b[39;00m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;66;03m# The program below will reveal what error will arise from our code.  \u001b[39;00m\n\u001b[0;32m----> 6\u001b[0m arithmetic \u001b[38;5;241m=\u001b[39m \u001b[38;5;241;43m5\u001b[39;49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[38;5;241;43m0\u001b[39;49m\n\u001b[1;32m      7\u001b[0m \u001b[38;5;28mprint\u001b[39m(arithmetic)\n",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "# 2. ZeroDivisionError\n",
    "\n",
    "# How to identify an ArithmeticError:\n",
    "# The program below will reveal what error will arise from our code.  \n",
    "\n",
    "arithmetic = 5/0\n",
    "print(arithmetic)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "432ade40-ce6a-46c6-9853-4afefdddd835",
   "metadata": {},
   "outputs": [],
   "source": [
    "# This is a type of ArithmeticError.\n",
    "\n",
    "# Mathematically, dividing an integer by zero is wrong, and that is the reason \n",
    "# why Python crashes the program and returns an error message."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "6da3f7dc-b682-40ae-87a2-a617096333ea",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "You have just made an Arithmetic error\n"
     ]
    }
   ],
   "source": [
    "# How to handle an ArithmeticError\n",
    "\n",
    "# Now, let us see how we can catch any of these errors in our code.\n",
    "try:\n",
    "  arithmetic = 5/0\n",
    "  print(arithmetic)\n",
    "except ArithmeticError:\n",
    "  print('You have just made an Arithmetic error')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "73a5180a-3ec2-4563-b284-5e7563f45a57",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Explanation:\n",
    "# 1: We introduce the try, except block to help us check for errors in our line of codes.\n",
    "# 2: We create a variable, arithmetic.\n",
    "# 3: We return the output of our variable.\n",
    "# 4: We use except to check for an ArithmeticError and complete the block.\n",
    "# 5: If there is an ArithmeticError in our code, we have previously told Python to return \n",
    "#    a text output instead of crashing our program.\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "96654cf5-8b54-45d3-8117-f5448aa7d674",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "\"\"\"\n",
    "The LookupError exception in Python forms the base class for all exceptions that are \n",
    "raised when an index or a key is not found for a sequence or dictionary respectively.\n",
    "\n",
    "You can use LookupError exception class to handle both IndexError and KeyError exception classes.\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "d658d1c3-5b02-4410-9a4a-2ee2abd5b1e9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "list index out of range, <class 'IndexError'>\n",
      "string index out of range, <class 'IndexError'>\n",
      "tuple index out of range, <class 'IndexError'>\n"
     ]
    }
   ],
   "source": [
    "# Example 1 - Handling IndexError exception\n",
    "# lists\n",
    "# lists\n",
    "x = [1, 2, 3, 4]\n",
    "try:\n",
    "    print(x[10])\n",
    "except LookupError as e:\n",
    "    print(f\"{e}, {e.__class__}\")\n",
    "\n",
    "\n",
    "\n",
    "# strings\n",
    "x = \"Pylenin\"\n",
    "try:\n",
    "    print(x[10])\n",
    "except LookupError as e:\n",
    "    print(f\"{e}, {e.__class__}\")\n",
    "\n",
    " \n",
    "    \n",
    "# tuples\n",
    "x = (1, 2, 3, 4)\n",
    "try:\n",
    "    print(x[10])\n",
    "except LookupError as e:\n",
    "    print(f\"{e}, {e.__class__}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "2399cd6c-18b0-42ae-8233-a6c331e0e147",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "What do you want to know about Dr. Jaishri Gothania==>  name\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "'name', <class 'KeyError'>\n"
     ]
    }
   ],
   "source": [
    "# Example 2 - Handling KeyError exception\n",
    "\n",
    "jaishri_info = {'Profession': 'Teaching',\n",
    "                'age': 30,\n",
    "                'language': 'Python'}\n",
    "user_input = input('What do you want to know about Dr. Jaishri Gothania==> ')\n",
    "\n",
    "try:\n",
    "    print(f'{user_input} is {jaishri_info[user_input]}')\n",
    "except LookupError as e:\n",
    "    print(f'{e}, {e.__class__}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "bf846f8e-ba1d-444e-9341-501519abc3b5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No module named 'exception'\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "module 'sys' has no attribute 'exc_type'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[17], line 13\u001b[0m\n\u001b[1;32m     12\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m---> 13\u001b[0m     \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mexception\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m myexception\n\u001b[1;32m     14\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'exception'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[17], line 16\u001b[0m\n\u001b[1;32m     14\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     15\u001b[0m     \u001b[38;5;28mprint\u001b[39m(e)\n\u001b[0;32m---> 16\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\u001b[43msys\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexc_type\u001b[49m)\n",
      "\u001b[0;31mAttributeError\u001b[0m: module 'sys' has no attribute 'exc_type'"
     ]
    }
   ],
   "source": [
    "# Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "# ImportError:\n",
    "    # This error generally occurs when a class cannot be imported due to one of the following reasons:\n",
    "    # The imported class is in a circular dependency.\n",
    "    # The imported class is unavailable or was not created.\n",
    "    # The imported class name is misspelled.\n",
    "    # The imported class from a module is misplaced.\n",
    "    # The imported class is unavailable in the Python library.\n",
    "# ModuleNotFoundError:    \n",
    "    # The 'module not found' error is a syntax error that appears when the static import statement \n",
    "    # cannot find the file at the declared path.\n",
    "\n",
    "import sys\n",
    "try:\n",
    "    from exception import myexception\n",
    "except Exception as e:\n",
    "    print(e)\n",
    "    print(sys.exc_type)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3f03e723-e4e4-4aaa-b75e-26b9d47da0dd",
   "metadata": {},
   "outputs": [],
   "source": [
    "# If from X import Y is used and Y cannot be found inside the module X, an ImportError is raised."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8cb8e61a-f98d-4477-aa53-4a1ead2c0135",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Q6. List down some best practices for exception handling in python.\n",
    "\n",
    "# 1. Use Exceptions for Exceptional Cases: Exceptions are, by definition, exceptional. They indicate that \n",
    "                                           something went wrong that was not expected to go wrong. If you \n",
    "                                           find yourself using exceptions for control flow, or for anything \n",
    "                                           other than exceptional cases, then you’re probably doing it wrong. \n",
    "                                           Exceptions are slow, and they can make code harder to read and \n",
    "                                           understand.\n",
    "                                           So what counts as an exceptional case? Here are some examples:\n",
    "                                                – A network connection is refused\n",
    "                                                – A file cannot be opened\n",
    "                                                – A database query returns no results\n",
    "\n",
    "                                            These are all cases where something went wrong that was not expected \n",
    "                                            to go wrong. If you find yourself using exceptions for anything other \n",
    "                                            than these sorts of cases, then you’re probably doing it wrong.\n",
    "                                            \n",
    "                                            \n",
    "# 2. Don’t Swallow the Exception:  When you “swallow” an exception, you essentially ignore it. This is bad for \n",
    "                                   a few reasons. For one, if the exception was caused by a bug in your code, \n",
    "                                   swallowing it means that the bug will never be fixed. The exception will \n",
    "                                   just keep happening and nobody will know about it or be able to do anything \n",
    "                                   about it.  \n",
    "                                   Finally, swallowing exceptions is generally considered bad practice because \n",
    "                                   it goes against the principle of “fail early, fail often.” Failing early means \n",
    "                                   failing as soon as possible so that you can fix the problem and move on. \n",
    "                                   Failing often means failing frequently so that you get used to it and become \n",
    "                                   better at dealing with failures. \n",
    "\n",
    "# 3. Catch Specific Exceptions: When you catch a general exception, like Exception, you’re catching everything. \n",
    "                                This includes system-level errors that are unlikely to be handled gracefully by \n",
    "                                your code. It’s better to be explicit about which exceptions you want to catch, \n",
    "                                so you can handle them appropriately.\n",
    "                                It’s also important to remember that when you catch an exception, you’re \n",
    "                                essentially saying “I know this might happen, and I’m prepared to deal with it.” \n",
    "                                By being specific about which exceptions you’re catching, you’re conveying \n",
    "                                confidence in your code.\n",
    "\n",
    "# 4. Always Clean Up Resources in a Finally Block: Suppose you have a file that you need to open, read from, and\n",
    "                                                   then close. If an exception occurs while reading from the file,\n",
    "                                                   you’ll want to make sure the file is properly closed before \n",
    "                                                   moving on. Otherwise, you risk leaving the file in an \n",
    "                                                   inconsistent state or even corrupting it.\n",
    "\n",
    "                                The best way to ensure the file is properly closed is to put the code for closing \n",
    "                                it in a finally block. That way, whether or not an exception occurs, the file will\n",
    "                                always be closed before the program continues.  \n",
    "                            \n",
    "# 5. Avoid Raising Generic Exceptions: When you raise a generic exception, such as Exception or RuntimeError, \n",
    "                                    you are essentially saying “I don’t know what went wrong, but something did.” \n",
    "                                    This is not helpful for either you or your users. It’s much better to be \n",
    "                                    specific about the error that occurred.\n",
    "\n",
    "                    For example, if you’re writing a function to parse a date from a string, and the string is in \n",
    "                    an invalid format, it’s better to raise a ValueError than a generic Exception. That way, you \n",
    "                    can handle the specific error case, and your users will know exactly what went wrong.\n",
    "\n",
    "                    Of course, there are times when you really don’t know what went wrong, and in those cases, \n",
    "                    a generic exception may be appropriate. But in general, it’s best to be specific.       \n",
    "                    \n",
    "# 6. Raise Custom Exceptions:When you’re writing code, it’s important to think about what could go wrong and plan \n",
    "                            for those contingencies. That way, if something does go wrong, your code can \n",
    "                            gracefully handle the error instead of crashing.\n",
    "\n",
    "                            One way to do this is to raise custom exceptions. By raising a custom exception, \n",
    "                            you can provide a specific error message that will be displayed to the user. \n",
    "                            This is helpful because it can give the user a clue as to what went wrong and \n",
    "                            how to fix it.\n",
    "\n",
    "                            For example, let’s say you’re writing a function to calculate the average of a \n",
    "                            list of numbers. If the list is empty, then the average can’t be calculated. \n",
    "                            In this case, you would want to raise a custom exception with an error message \n",
    "                            like “The list is empty. Cannot calculate the average.”      \n",
    "                            \n",
    "# 7. Define Your Own Exception Hierarchy: When you’re writing code that deals with exceptions, you’ll find \n",
    "                                        yourself handling different types of exceptions in different ways. \n",
    "                                        For example, you might want to log an error and exit gracefully when \n",
    "                                        you encounter a SystemExit exception, but you might want to just log \n",
    "                                        an error when you encounter an ImportError.\n",
    "\n",
    "                            By defining your own exception hierarchy, you can write code that handles different \n",
    "                            types of exceptions in the way that makes the most sense for each type. This will \n",
    "                            make your code more robust and easier to maintain.\n",
    "                            \n",
    "# 8. Document All Exceptions Thrown by a Function: If you don’t document the exceptions thrown by a function, \n",
    "                                                then other developers who use that function won’t know what to \n",
    "                                                expect. This can lead to unexpected behavior, and can even cause \n",
    "                                                errors in production if an exception is raised that wasn’t \n",
    "                                                anticipated.\n",
    "\n",
    "                            Documenting exceptions is also important for code maintainability. If you need to \n",
    "                            change the way a function behaves when an exception is raised, you’ll need to update \n",
    "                            the documentation accordingly. Otherwise, other developers might not be aware of the \n",
    "                            change, and they could end up writing code that doesn’t work as expected. \n",
    "                            \n",
    "# 9. Provide Contextual Information When Raising an Exception: When an exception is raised, the Python interpreter \n",
    "                                                        stops execution of the program and prints out a traceback. \n",
    "                                                        The traceback starts with the line where the exception was \n",
    "                                                        raised and includes the lines of code that were executed \n",
    "                                                        leading up to that point.\n",
    "\n",
    "                            If you provide contextual information when raising an exception, it will be included\n",
    "                            in the traceback and will help the person who is debugging the code to understand what\n",
    "                            went wrong. For example, if you’re raising an exception because a file could not be \n",
    "                            found, you should include the name of the file in the exception message.  \n",
    "                            \n",
    "# 10. Write Tests to Ensure That Exceptions Are Raised Correctly: If you don’t write tests, you can’t be sure that\n",
    "                                                                your code is actually raising the exceptions you \n",
    "                                                                think it is. This can lead to all sorts of\n",
    "                                                                problems down the line, including hard-to-find \n",
    "                                                                bugs and unexpected behavior.\n",
    "\n",
    "                            Writing tests also forces you to think about what should happen when an exception is \n",
    "                            raised, which can help you design your code in a more robust and resilient way.                            "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
